version: "3"

tasks:
  kubespray-venv:
    desc: Create the virtual environment for Kubespray
    cmds:
      - echo "Creating virtual environment."
      - python3 -m venv {{.VENV_DIR}}
      - echo "Ensuring environment requirements are installed"
      - {{.VENV_DIR}}/bin/python -m pip install --upgrade wheel pip
      - {{.VENV_DIR}}/bin/pip install -U -r {{.KUBESPRAYDIR}}/requirements.txt
      - echo "Virtual environment '{{.VENV_NAME}}' created at {{.VENV_DIR}}."
      - echo "Activate it using 'source {{.VENV_DIR}}/activate'"

  link-clusters:
    desc: Link cluster directories to the Kubespray inventory
    cmds:
      - echo "Adding clusters to kubespray inventory"
      - for dir in {{.SUBDIRS}}; do
          cluster_name="$(basename "$$dir")";
          symlink="{{.CLUSTERS_DEST_DIR}}/$$cluster_name";
          if [ ! -e "$$symlink" ]; then
            ln -s "$$dir" "$$symlink";
            echo "Created symlink for $$cluster_name";
          else
            echo "Symlink for $$cluster_name already exists";
          fi
        done

  setup-kubespray:
    desc: Set up Kubespray environment
    deps:
      - kubespray-venv
      - link-clusters
    cmds:
      - echo "Kubespray setup complete."

vars:
  KUBESPRAYDIR: kubespray
  VENV_NAME: kubespray-venv
  VENV_DIR: $(HOME)/.python/$(VENV_NAME)
  CLUSTERS_SOURCE_DIR: $(PWD)/clusters
  CLUSTERS_DEST_DIR: $(PWD)/kubespray/inventory
  SUBDIRS: $(wildcard $(CLUSTERS_SOURCE_DIR)/*)

default: setup-kubespray
